config/routes.rb
Mu::Application.routes.draw do
  resources :transactions

  devise_for :users
  root "transactions#index"
  get "about" => "pages#about" # create about_path
  

  

end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates :category, presence: true
	validates :amount, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 	has_many :transactions

 	validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @transactions = Transaction.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 2)
  end

  def show
  end

  def new
    @transaction = current_user.transactions.build
  end

  def edit
  end

  def create
    @transaction = current_user.transactions.build(transaction_params)

    if @transaction.save
      redirect_to @transaction, notice: 'Transaction was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @transaction.update(transaction_params)
      redirect_to @transaction, notice: 'Transaction was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @transaction.destroy
    redirect_to transactions_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    def correct_user
      @transaction = current_user.transactions.find_by(id: params[:id])
      redirect_to transactions_path, notice: "Not authorized to edit this transaction" if @transaction.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:category, :date, :amount, :location, :account, :tag, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "The World of Mu", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>  
        <% if user_signed_in? %>
          <li>
            <%= link_to new_transaction_path do %>
              <span class="glyphicon glyphicon-plus"></span> New transaction
            <% end %>
          </li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %> 
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mu</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
	<h1>Welcome to The World of Mu</h1>
	<p>
		<%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
		<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
	</p>	
</div>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>We are working on The World of MU, the first gamified personal finance app.</p>

app/views/transactions/_form.html.erb
<%= form_for @transaction, html: { multipart: true } do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :category %><br>
    <%= f.select :category, [['Living'], ['Spending']], :prompt => true, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :amount %><br>
    <%= f.text_field :amount, class: "form-control"  %>
  </div>
  
  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :account %><br>
    <%= f.text_field :account, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :tag %><br>
    <%= f.text_field :tag, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @transactions.each do |transaction| %>

    <div class="box panel panel-default">
      <%= link_to image_tag(transaction.image.url(:medium)), transaction %>

      <div class="panel-body">
        <p><%= transaction.category %></p>
        <p><%= transaction.date.to_formatted_s(:long_ordinal) %></p>
        <p><%= transaction.amount %></p>
        <p><%= transaction.location %></p>
        <p><%= transaction.account %></p>
        <p><%= transaction.tag %></p>
        <p><strong><%= transaction.user.name if transaction.user %></strong></p>

        <% if transaction.user == current_user %>
          <div class="actions">
          <%= link_to edit_transaction_path(transaction) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
          <% end %>
          <%= link_to transaction, method: :delete, data: { confirm: 'Are you sure?' } do %>
          <span class="glyphicon glyphicon-trash"></span>
            Delete
          <% end %>
          </div>
        <% end %>
       </div>
    </div>
  <% end %>
</div>

<div class="center">
  <%= will_paginate @transactions, renderer: BootstrapPagination::Rails %>
</div>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<%= link_to 'Back', transactions_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
    <div class="panel-heading center">
      <%= image_tag @transaction.image.url(:medium) %>
    </div>
    <div class="panel-body">

      <p>
        <strong>Category:</strong>
        <%= @transaction.category %>
      </p>
  
      <p>
        <strong>Date:</strong>
        <%= @transaction.date.to_formatted_s(:long_ordinal) %>
      </p>

      <p>
        <strong>Amount:</strong>
        <%= @transaction.amount %>
      </p>

      <p>
        <strong>Location:</strong>
        <%= @transaction.location %>
      </p>

      <p>
        <strong>Account:</strong>
        <%= @transaction.account %>
      </p>

      <p>
        <strong>Tag:</strong>
        <%= @transaction.tag %>
      </p>

      <p>
        <strong><%= @transaction.user.name if @transaction.user %></strong>
      </p>

      <% if @transaction.user == current_user %>
        <%= link_to edit_transaction_path(@transaction) do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit
          <% end %>
      <% end %>
    </div>
  </div>
</div>